### ISSUE TITLE
OS X makefile has linked binary in includes

### ISSUE THREAD

**Issue by daanmichiels** [daanmichiels/igl-hr#13]
One of the includes in Makefile.osx is actually a binary. That's wrong. Libraries should be linked using LIBPATHS and LIBRARIES.

**Comment by daanmichiels** [comment]
Daniel, could you check whether this is still the case, and close the issue if not?

**Comment by dpugliese36** [comment]
link to binary has been moved to LIBPATHS, only directories are in INCLUDES now
