### ISSUE TITLE
Rectangle primitive broken

### ISSUE THREAD

**Issue by daanmichiels** [daanmichiels/igl-hr#5]
In commit 4969367ac7668a857dd5d03a9db7beb9ae3b667f, it seems that the rectangle primitive is broken. Increasing the length of the rectangle (hr.cpp, line 88, change 2.0 to 8.0) makes it narrower.

**Comment by daanmichiels** [comment]
Status?

**Comment by mcdaniel67** [comment]
This is still broken. I've tried a couple different methods to fix this using GL_TRIANGLES, GL_QUADS, and GL_TRIANGLE_FAN last semester, but I never got the issue fixed. I have a few more ideas of things to try.

**Comment by mcdaniel67** [comment]
The bug was in our intuition, not in the programming. We can see this by making the rectangle extremely small, thus making the curvature near euclidean. This made the rectangles appear correctly.
